import {describe,it,expect,vi,afterEach} from "vitest";
import {buildNativeApp} from "../src/native-app.js";
import {parseEnv} from "../src/config/env.js";
const body={first_name:"Ada",last_name:"Test",email:"ada@example.test",phone:"0812345678",password:"test-password-123"};
const reviewed={request_id:"r1",first_name:"Ada",last_name:"Test",email:"ada@example.test",phone:"+243812345678",status:"pending"};
function fixture(enabled=true,fail?:string){
 const query=vi.fn(async(sql:string,params:unknown[])=>{if(fail)throw Object.assign(Error("private SQL detail"),{code:fail});if(sql.includes("review"))return {rows:[{result:reviewed}]};if(sql.includes("decide"))return {rows:[{result:{request_id:"r1",status:params[1]==="approve"?"approved":"rejected"}}]};return {rows:[{result:{request_id:"r1",status:"pending"}}]}});
 const env=parseEnv({NODE_ENV:"test",...(enabled?{SCHOOLSAFE_GOOGLE_MAIL_URL:"https://google.example.test",SCHOOLSAFE_GOOGLE_MAIL_SECRET:"synthetic-test-secret",SCHOOLSAFE_APPROVAL_URL:"https://example.test/approval"}:{})});
 const app=buildNativeApp(env,{authPool:{query,end:vi.fn()},businessPool:{query:vi.fn(),end:vi.fn()}} as any);return {app,query};
}
afterEach(()=>vi.unstubAllGlobals());
describe("native app registration wiring",()=>{
 it.each([false,true])("exposes only boolean availability with Google configuration %s",async enabled=>{const {app}=fixture(enabled);try{const res=await app.inject({url:"/config"});expect(res.json()).toEqual({auth_mode:"native",setup_available:false,account_registration_available:enabled});expect(res.body).not.toContain("synthetic");expect(res.body).not.toContain("https:")}finally{await app.close()}});
 it("registers through the real app assembly with mock Google",async()=>{vi.stubGlobal("fetch",vi.fn().mockResolvedValue(new Response('{"ok":true,"provider":"google-mail"}')));const {app,query}=fixture();try{const res=await app.inject({method:"POST",url:"/auth/registrations",payload:body});expect(res.statusCode).toBe(202);expect(res.json()).toEqual({request_id:"r1",status:"pending"});expect(query.mock.calls[0][1][2]).toBe("127.0.0.1");expect(res.body).not.toContain("password")}finally{await app.close()}});
 it("disabled configuration returns 503 before SQL",async()=>{const {app,query}=fixture(false);try{expect((await app.inject({method:"POST",url:"/auth/registrations",payload:body})).statusCode).toBe(503);expect(query).not.toHaveBeenCalled()}finally{await app.close()}});
 it.each([["23505",409],["P0001",429],["23514",400]])("sanitizes registration SQL %s",async(code,status)=>{const {app}=fixture(true,code as string);try{const res=await app.inject({method:"POST",url:"/auth/registrations",payload:body});expect(res.statusCode).toBe(status);expect(res.body).not.toContain("private SQL")}finally{await app.close()}});
 it.each(["review","decision"])("has no GET %s capability route",async action=>{const {app}=fixture();try{expect((await app.inject({url:"/auth/registrations/"+action+"?token="+"a".repeat(43)})).statusCode).toBe(404)}finally{await app.close()}});
 it.each([{}, {token:"bad"},{token:"a".repeat(43),extra:true}])("denies malformed review generically",async payload=>{const {app,query}=fixture();try{const res=await app.inject({method:"POST",url:"/auth/registrations/review",payload});expect(res.statusCode).toBe(403);expect(res.json().code).toBe("ACCESS_DENIED");expect(query).not.toHaveBeenCalled()}finally{await app.close()}});
 it("returns exact normalized review and decision, never raw token",async()=>{const {app}=fixture();try{const review=await app.inject({method:"POST",url:"/auth/registrations/review",payload:{token:"a".repeat(43)}});expect(review.json()).toEqual(reviewed);const decision=await app.inject({method:"POST",url:"/auth/registrations/decision",payload:{token:"a".repeat(43),decision:"approve"}});expect(decision.json()).toEqual({request_id:"r1",status:"approved"})}finally{await app.close()}});
});

describe("registration boundary checks",()=>{
 it("rejects malformed JSON with a sanitized validation response",async()=>{const {app,query}=fixture();try{const res=await app.inject({method:"POST",url:"/auth/registrations",headers:{"content-type":"application/json"},payload:'{"password":'});expect(res.statusCode).toBe(400);expect(res.body).not.toContain("password");expect(query).not.toHaveBeenCalled()}finally{await app.close()}});
 it.each(["SCHOOLSAFE_GOOGLE_MAIL_URL","SCHOOLSAFE_GOOGLE_MAIL_SECRET","SCHOOLSAFE_APPROVAL_URL"])("requires configuration %s",async missing=>{const config:Record<string,string>={NODE_ENV:"test",SCHOOLSAFE_GOOGLE_MAIL_URL:"https://google.example.test",SCHOOLSAFE_GOOGLE_MAIL_SECRET:"synthetic-test-secret",SCHOOLSAFE_APPROVAL_URL:"https://example.test"};delete config[missing];const app=buildNativeApp(parseEnv(config),{authPool:{query:vi.fn(),end:vi.fn()},businessPool:{query:vi.fn(),end:vi.fn()}} as any);try{expect((await app.inject({url:"/config"})).json().account_registration_available).toBe(false)}finally{await app.close()}});
 it.each([{SCHOOLSAFE_GOOGLE_MAIL_URL:"http://google.example.test"},{SCHOOLSAFE_GOOGLE_MAIL_URL:"https://user:password@google.example.test"},{SCHOOLSAFE_GOOGLE_MAIL_SECRET:" "}])("rejects invalid runtime configuration %j",env=>expect(()=>parseEnv(env)).toThrow());
 it.each(["approve","reject"])("denies expired or consumed %s decisions generically",async decision=>{const {app}=fixture(true,"42501");try{const res=await app.inject({method:"POST",url:"/auth/registrations/decision",payload:{token:"a".repeat(43),decision}});expect(res.statusCode).toBe(403);expect(res.json().code).toBe("ACCESS_DENIED");expect(res.body).not.toContain("private SQL")}finally{await app.close()}});
});
