import {describe,it,expect,vi} from "vitest";
import {buildNativeApp} from "../src/native-app.js";
import {parseEnv} from "../src/config/env.js";
import {hashSessionToken} from "../src/authnative/tokens.js";
const token="a".repeat(43),cookie="schoolsafe_onboarding="+token;
const identity={first_name:"Ada",last_name:"Test",email:"ada@example.test",phone:"+243812345678",status:"approved"};
const school={identity:{name_fr:" Test School "},cycles:["primary"],academic_year:{label:"2026-2027",starts_on:"2026-09-01",ends_on:"2027-07-01"},contact:{country:"RDC",province:"Province",city:"City",address:"Address",email:"school@example.test",phone:"+243812345678",website_url:"https://example.test",website_mode:"Mode",public_news:"News",public_gallery:"Gallery",public_honors:"Honors"},brand:{primary_color:"#112233",accent_color:"#abcdef",document_footer:"Footer"}};
function fixture(valid=true,fail?:string){const query=vi.fn(async(sql:string,_params:unknown[])=>{if(fail)throw Object.assign(Error("private SQL detail"),{code:fail});if(sql.includes("resolve_onboarding_session"))return {rows:[{result:valid?identity:null}]};return {rows:[{result:{school_id:"school",profile_id:"profile",status:"completed"}}]}});const app=buildNativeApp(parseEnv({NODE_ENV:"test"}),{authPool:{query,end:vi.fn()},businessPool:{query:vi.fn(),end:vi.fn()}} as any);return {app,query}}
describe("onboarding cookie routes",()=>{
 it("resolves approved account with hashed cookie and no Google configuration",async()=>{const {app,query}=fixture();try{const res=await app.inject({url:"/auth/onboarding/me",headers:{cookie}});expect(res.json()).toEqual(identity);expect(query.mock.calls[0][1]).toEqual([hashSessionToken(token)])}finally{await app.close()}});
 it.each([{}, {cookie:"schoolsafe_session="+token}])("refuses query token and other cookie %j",async headers=>{const {app,query}=fixture();try{expect((await app.inject({url:"/auth/onboarding/me?token="+token,headers})).statusCode).toBe(401);expect(query).not.toHaveBeenCalled()}finally{await app.close()}});
 it("refuses expired cookie",async()=>{const {app}=fixture(false);try{expect((await app.inject({url:"/auth/onboarding/me",headers:{cookie}})).statusCode).toBe(401)}finally{await app.close()}});
 it("creates school from cookie capability, preserves all contacts and brand and clears cookie",async()=>{const {app,query}=fixture();try{const res=await app.inject({method:"POST",url:"/auth/onboarding/school",headers:{cookie},payload:school});expect(res.statusCode).toBe(201);expect(res.json()).toEqual({school_id:"school",profile_id:"profile",status:"completed"});const call=query.mock.calls.find(([sql])=>sql.includes("account_onboarding_create_school"))!;expect(call[1][0]).toBe(hashSessionToken(token));const sent=JSON.parse(call[1][1] as string);expect(sent.contact).toEqual(school.contact);expect(sent.brand).toEqual(school.brand);expect(sent.identity.name_fr).toBe("Test School");expect(sent.academic_year.periods).toBe("Trimestres");expect(res.headers["set-cookie"]).toContain("Max-Age=0")}finally{await app.close()}});
 it.each([{admin:{}},{password:"secret"},{school_id:"fake"},{logoBase64:"data:abc"},{identity:{name_fr:" "}},{cycles:[]},{cycles:["bad"]},{academic_year:{...school.academic_year,starts_on:"2028-01-01"}},{academic_year:{...school.academic_year,ends_on:"bad"}},{brand:{logo_path:"data:abc"}},{contact:{...school.contact,extra:"x"}}])("rejects invalid school %j",async change=>{const {app,query}=fixture();try{expect((await app.inject({method:"POST",url:"/auth/onboarding/school",headers:{cookie},payload:{...school,...change}})).statusCode).toBe(400);expect(query).not.toHaveBeenCalled()}finally{await app.close()}});
 it.each([{origin:"https://evil.example"},{"sec-fetch-site":"cross-site"},{"content-type":"text/plain"}])("rejects cross-site or non-JSON mutation %j",async extra=>{const {app,query}=fixture();try{const res=await app.inject({method:"POST",url:"/auth/onboarding/school",headers:{cookie,...extra},payload:extra["content-type"]?JSON.stringify(school):school});expect([400,403,415]).toContain(res.statusCode);expect(query).not.toHaveBeenCalled()}finally{await app.close()}});
 it.each([["42501",403],["23514",400],["22007",400],["XX000",503]])("sanitizes school SQL %s",async(code,status)=>{const {app}=fixture(true,code as string);try{const res=await app.inject({method:"POST",url:"/auth/onboarding/school",headers:{cookie},payload:school});expect(res.statusCode).toBe(status);expect(res.body).not.toContain("private SQL")}finally{await app.close()}});
 it("logout revokes by hash and clears cookie",async()=>{const {app,query}=fixture();try{const res=await app.inject({method:"POST",url:"/auth/onboarding/logout",headers:{cookie},payload:{}});expect(res.statusCode).toBe(200);expect(query.mock.calls[0][0]).toContain("revoke_onboarding_session");expect(query.mock.calls[0][1]).toEqual([hashSessionToken(token)]);expect(res.headers["set-cookie"]).toContain("Max-Age=0")}finally{await app.close()}});
});
